services:
  - type: web
    name: novamind-backend
    env: python
    plan: free
    region: oregon
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      python -m venv spleeter_env
      ./spleeter_env/bin/pip install --upgrade pip
      ./spleeter_env/bin/pip install spleeter==2.4.0
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn -w 1 -k gthread -t 900 app:app
    envVars:
      - key: SPLEETER_BIN
        value: /opt/render/project/src/spleeter_env/bin/spleeter
      - key: REBUILD_INTERVAL_SECONDS
        value: "1800"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHON_VERSION
        value: 3.9.18
    healthCheckPath: /health
    autoDeploy: true

