services:
  - type: web
    name: novamind-backend
    env: python
    plan: free
    region: oregon
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn -w 1 -k gthread -t 900 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: SEPARATION_MODE
        value: ffmpeg
      - key: REBUILD_INTERVAL_SECONDS
        value: "1800"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHON_VERSION
        value: 3.9.18
    healthCheckPath: /health
    autoDeploy: true

